repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        args: ["--line-length=125"]
        types: [file, python]

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--line-length=125", "--profile=black"]
        types: [file, python]

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args: ["--max-line-length=125", "--max-complexity=10"]
        types: [file, python]

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.1
    hooks:
      - id: autopep8
        args:
          [
            '--ignore=["E203","W503","W605"]',
            "--max-line-length=125",
            "--in-place"
          ]
        types: [file, python]

  - repo: https://github.com/aws-samples/automated-security-helper
    rev: 'v1.5.1'
    hooks:
        - id: ash
          stages: [ manual ]
          # uncomment the line below if using "finch" on MacOS
          # args: [ "-f" ]

  - repo: https://github.com/sbrunner/pre-commit-copyright
    rev: 0.7.0
    hooks:
      - id: copyright
        name: update copyright
        exclude: |
          (?x)^(
            doc/.*|
            ^\..+|
            .+\.md|
            test/data/.*|
            LICENSE|
            tox.ini|
            pyproject.toml|
            setup.cfg|
            setup.py|
            py.typed|
            test-integ/aws/osml/tile_server/data/.*
          )$
      - id: copyright-required
        name: require copyright
        exclude: |
          (?x)^(
            doc/.*|
            ^\..+|
            .+\.md|
            test/data/.*|
            LICENSE|
            tox.ini|
            pyproject.toml|
            setup.cfg|
            setup.py|
            py.typed|
            test-integ/aws/osml/tile_server/data/.*
          )$
