version: "3.8"
services:
  tile-server:
    build:
      context: .
    container_name: "osml-tile-server"
    ports:
      - '8080:8080'
    environment:
      - GDAL_CACHEMAX=2048
      - GDAL_NUM_THREADS=ALL_CPUS
      - WEB_CONCURRENCY=1
      - EFS_MOUNT_NAME=/tmp/local_viewpoint_cache
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
    volumes:
      - "/tmp/local_viewpoint_cache:/tmp/viewpoint:rw"
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    cap_add:
      - SYS_PTRACE
