# Copyright 2023-2024 Amazon.com, Inc. or its affiliates.

version: "3.8"
services:
  tile-server:
    build:
      context: ..
      dockerfile: Dockerfile.tile_server
    container_name: "osml-tile-server"
    user: root
    ports:
      - '8080:8080'
    environment:
      - GDAL_CACHEMAX=2048
      - GDAL_NUM_THREADS=ALL_CPUS
      - WEB_CONCURRENCY=1
      - EFS_MOUNT_NAME=tmp/viewpoint
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_DEFAULT_REGION
    volumes:
      - "/tmp/local_viewpoint_cache:/tmp/viewpoint:rw"
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    cap_add:
      - SYS_PTRACE
