# Copyright 2023-2024 Amazon.com, Inc. or its affiliates.

name: osml_tile_server
channels:
  - conda-forge
dependencies:
  - conda-forge::cryptography=42.0.2
  - conda-forge::gdal=3.8.3
  - conda-forge::proj=9.3.1
