# Copyright 2023-2024 Amazon.com, Inc. or its affiliates.

name: osml-ts-locust-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - locust
      - boto3
      - hilbertcurve
      - py-spy
