name: docker build

on:
  workflow_call:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: 'true'
    - name: Build the Docker Container
      run: docker build . --file docker/Dockerfile.tile_server --tag osml-tile-server:$(date +%s)
