name: Build Docker Container

on:
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        lfs: 'true'
        ssh-key: ${{ secrets.git_ssh_key }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag osml-tile-server:$(date +%s)
